package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * Acteurfilm generated by hbm2java
 */
public class Acteurfilm  implements java.io.Serializable {


     private Long idacteur;
     private Personnefilm personnefilm;
     private Film film;
     private String nompersonnage;

    public Acteurfilm() {
    }

    public Acteurfilm(Long idacteur, Personnefilm personnefilm, Film film, String nompersonnage) {
       this.idacteur = idacteur;
       this.personnefilm = personnefilm;
       this.film = film;
       this.nompersonnage = nompersonnage;
    }
   
    public Long getIdacteur() {
        return this.idacteur;
    }
    
    public void setIdacteur(Long idacteur) {
        this.idacteur = idacteur;
    }
    public Personnefilm getPersonnefilm() {
        return this.personnefilm;
    }
    
    public void setPersonnefilm(Personnefilm personnefilm) {
        this.personnefilm = personnefilm;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public String getNompersonnage() {
        return this.nompersonnage;
    }
    
    public void setNompersonnage(String nompersonnage) {
        this.nompersonnage = nompersonnage;
    }




}


