package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String idutilisateur;
     private Forfait forfait;
     private String typecarte;
     private String numerocarte;
     private Date dateexpirationcarte;

    public Client() {
    }

    public Client(String idutilisateur, Forfait forfait, String typecarte, String numerocarte, Date dateexpirationcarte) {
       this.idutilisateur = idutilisateur;
       this.forfait = forfait;
       this.typecarte = typecarte;
       this.numerocarte = numerocarte;
       this.dateexpirationcarte = dateexpirationcarte;
    }
   
    public String getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(String idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Forfait getForfait() {
        return this.forfait;
    }
    
    public void setForfait(Forfait forfait) {
        this.forfait = forfait;
    }
    public String getTypecarte() {
        return this.typecarte;
    }
    
    public void setTypecarte(String typecarte) {
        this.typecarte = typecarte;
    }
    public String getNumerocarte() {
        return this.numerocarte;
    }
    
    public void setNumerocarte(String numerocarte) {
        this.numerocarte = numerocarte;
    }
    public Date getDateexpirationcarte() {
        return this.dateexpirationcarte;
    }
    
    public void setDateexpirationcarte(Date dateexpirationcarte) {
        this.dateexpirationcarte = dateexpirationcarte;
    }




}


