package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Copie generated by hbm2java
 */
public class Copie  implements java.io.Serializable {


     private Long idcopie;
     private Film film;
     private String code;
     private String statut;
     private Set locationarchivees = new HashSet(0);
     private Set locationactives = new HashSet(0);

    public Copie() {
    }

	
    public Copie(Long idcopie, Film film, String code) {
        this.idcopie = idcopie;
        this.film = film;
        this.code = code;
    }
    public Copie(Long idcopie, Film film, String code, String statut, Set locationarchivees, Set locationactives) {
       this.idcopie = idcopie;
       this.film = film;
       this.code = code;
       this.statut = statut;
       this.locationarchivees = locationarchivees;
       this.locationactives = locationactives;
    }
   
    public Long getIdcopie() {
        return this.idcopie;
    }
    
    public void setIdcopie(Long idcopie) {
        this.idcopie = idcopie;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public Set getLocationarchivees() {
        return this.locationarchivees;
    }
    
    public void setLocationarchivees(Set locationarchivees) {
        this.locationarchivees = locationarchivees;
    }
    public Set getLocationactives() {
        return this.locationactives;
    }
    
    public void setLocationactives(Set locationactives) {
        this.locationactives = locationactives;
    }




}


