package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private Long idfilm;
     private Personnefilm personnefilm;
     private String titre;
     private short anneeparution;
     private String langueoriginale;
     private short duree;
     private Clob resumescenario;
     private Set scenaristefilms = new HashSet(0);
     private Set paysfilms = new HashSet(0);
     private Set acteurfilms = new HashSet(0);
     private Set copies = new HashSet(0);
     private Set genrefilms = new HashSet(0);

    public Film() {
    }

	
    public Film(Long idfilm, String titre, short anneeparution, String langueoriginale, short duree, Clob resumescenario) {
        this.idfilm = idfilm;
        this.titre = titre;
        this.anneeparution = anneeparution;
        this.langueoriginale = langueoriginale;
        this.duree = duree;
        this.resumescenario = resumescenario;
    }
    public Film(Long idfilm, Personnefilm personnefilm, String titre, short anneeparution, String langueoriginale, short duree, Clob resumescenario, Set scenaristefilms, Set paysfilms, Set acteurfilms, Set copies, Set genrefilms) {
       this.idfilm = idfilm;
       this.personnefilm = personnefilm;
       this.titre = titre;
       this.anneeparution = anneeparution;
       this.langueoriginale = langueoriginale;
       this.duree = duree;
       this.resumescenario = resumescenario;
       this.scenaristefilms = scenaristefilms;
       this.paysfilms = paysfilms;
       this.acteurfilms = acteurfilms;
       this.copies = copies;
       this.genrefilms = genrefilms;
    }
   
    public Long getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(Long idfilm) {
        this.idfilm = idfilm;
    }
    public Personnefilm getPersonnefilm() {
        return this.personnefilm;
    }
    
    public void setPersonnefilm(Personnefilm personnefilm) {
        this.personnefilm = personnefilm;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public short getAnneeparution() {
        return this.anneeparution;
    }
    
    public void setAnneeparution(short anneeparution) {
        this.anneeparution = anneeparution;
    }
    public String getLangueoriginale() {
        return this.langueoriginale;
    }
    
    public void setLangueoriginale(String langueoriginale) {
        this.langueoriginale = langueoriginale;
    }
    public short getDuree() {
        return this.duree;
    }
    
    public void setDuree(short duree) {
        this.duree = duree;
    }
    public Clob getResumescenario() {
        return this.resumescenario;
    }
    
    public void setResumescenario(Clob resumescenario) {
        this.resumescenario = resumescenario;
    }
    public Set getScenaristefilms() {
        return this.scenaristefilms;
    }
    
    public void setScenaristefilms(Set scenaristefilms) {
        this.scenaristefilms = scenaristefilms;
    }
    public Set getPaysfilms() {
        return this.paysfilms;
    }
    
    public void setPaysfilms(Set paysfilms) {
        this.paysfilms = paysfilms;
    }
    public Set getActeurfilms() {
        return this.acteurfilms;
    }
    
    public void setActeurfilms(Set acteurfilms) {
        this.acteurfilms = acteurfilms;
    }
    public Set getCopies() {
        return this.copies;
    }
    
    public void setCopies(Set copies) {
        this.copies = copies;
    }
    public Set getGenrefilms() {
        return this.genrefilms;
    }
    
    public void setGenrefilms(Set genrefilms) {
        this.genrefilms = genrefilms;
    }




}


