package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private Long idforfait;
     private String descripteur;
     private Short cout;
     private Short locationmax;
     private Short dureemax;
     private Set clients = new HashSet(0);

    public Forfait() {
    }

	
    public Forfait(Long idforfait, String descripteur) {
        this.idforfait = idforfait;
        this.descripteur = descripteur;
    }
    public Forfait(Long idforfait, String descripteur, Short cout, Short locationmax, Short dureemax, Set clients) {
       this.idforfait = idforfait;
       this.descripteur = descripteur;
       this.cout = cout;
       this.locationmax = locationmax;
       this.dureemax = dureemax;
       this.clients = clients;
    }
   
    public Long getIdforfait() {
        return this.idforfait;
    }
    
    public void setIdforfait(Long idforfait) {
        this.idforfait = idforfait;
    }
    public String getDescripteur() {
        return this.descripteur;
    }
    
    public void setDescripteur(String descripteur) {
        this.descripteur = descripteur;
    }
    public Short getCout() {
        return this.cout;
    }
    
    public void setCout(Short cout) {
        this.cout = cout;
    }
    public Short getLocationmax() {
        return this.locationmax;
    }
    
    public void setLocationmax(Short locationmax) {
        this.locationmax = locationmax;
    }
    public Short getDureemax() {
        return this.dureemax;
    }
    
    public void setDureemax(Short dureemax) {
        this.dureemax = dureemax;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


