package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * Genrefilm generated by hbm2java
 */
public class Genrefilm  implements java.io.Serializable {


     private GenrefilmId id;
     private Film film;
     private Genre genre;

    public Genrefilm() {
    }

    public Genrefilm(GenrefilmId id, Film film, Genre genre) {
       this.id = id;
       this.film = film;
       this.genre = genre;
    }
   
    public GenrefilmId getId() {
        return this.id;
    }
    
    public void setId(GenrefilmId id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }




}


