package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * GenrefilmId generated by hbm2java
 */
public class GenrefilmId  implements java.io.Serializable {


     private String idgenre;
     private String idfilm;

    public GenrefilmId() {
    }

    public GenrefilmId(String idgenre, String idfilm) {
       this.idgenre = idgenre;
       this.idfilm = idfilm;
    }
   
    public String getIdgenre() {
        return this.idgenre;
    }
    
    public void setIdgenre(String idgenre) {
        this.idgenre = idgenre;
    }
    public String getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(String idfilm) {
        this.idfilm = idfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenrefilmId) ) return false;
		 GenrefilmId castOther = ( GenrefilmId ) other; 
         
		 return ( (this.getIdgenre()==castOther.getIdgenre()) || ( this.getIdgenre()!=null && castOther.getIdgenre()!=null && this.getIdgenre().equals(castOther.getIdgenre()) ) )
 && ( (this.getIdfilm()==castOther.getIdfilm()) || ( this.getIdfilm()!=null && castOther.getIdfilm()!=null && this.getIdfilm().equals(castOther.getIdfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdgenre() == null ? 0 : this.getIdgenre().hashCode() );
         result = 37 * result + ( getIdfilm() == null ? 0 : this.getIdfilm().hashCode() );
         return result;
   }   


}


