package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Locationarchivee generated by hbm2java
 */
public class Locationarchivee  implements java.io.Serializable {


     private String idlocation;
     private Utilisateur utilisateur;
     private Copie copie;
     private Date datelocation;
     private Date dateretour;

    public Locationarchivee() {
    }

	
    public Locationarchivee(String idlocation, Utilisateur utilisateur, Date datelocation, Date dateretour) {
        this.idlocation = idlocation;
        this.utilisateur = utilisateur;
        this.datelocation = datelocation;
        this.dateretour = dateretour;
    }
    public Locationarchivee(String idlocation, Utilisateur utilisateur, Copie copie, Date datelocation, Date dateretour) {
       this.idlocation = idlocation;
       this.utilisateur = utilisateur;
       this.copie = copie;
       this.datelocation = datelocation;
       this.dateretour = dateretour;
    }
   
    public String getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(String idlocation) {
        this.idlocation = idlocation;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Copie getCopie() {
        return this.copie;
    }
    
    public void setCopie(Copie copie) {
        this.copie = copie;
    }
    public Date getDatelocation() {
        return this.datelocation;
    }
    
    public void setDatelocation(Date datelocation) {
        this.datelocation = datelocation;
    }
    public Date getDateretour() {
        return this.dateretour;
    }
    
    public void setDateretour(Date dateretour) {
        this.dateretour = dateretour;
    }




}


