package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Locationactive generated by hbm2java
 */
public class Locationactive  implements java.io.Serializable {


     private Long idlocation;
     private Utilisateur utilisateur;
     private Copie copie;
     private Date datelocation;

    public Locationactive() {
    }

    public Locationactive(Long idlocation, Utilisateur utilisateur, Copie copie, Date datelocation) {
       this.idlocation = idlocation;
       this.utilisateur = utilisateur;
       this.copie = copie;
       this.datelocation = datelocation;
    }
   
    public Long getIdlocation() {
        return this.idlocation;
    }
    
    public void setIdlocation(Long idlocation) {
        this.idlocation = idlocation;
    }
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }
    public Copie getCopie() {
        return this.copie;
    }
    
    public void setCopie(Copie copie) {
        this.copie = copie;
    }
    public Date getDatelocation() {
        return this.datelocation;
    }
    
    public void setDatelocation(Date datelocation) {
        this.datelocation = datelocation;
    }




}


