package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paysproduction generated by hbm2java
 */
public class Paysproduction  implements java.io.Serializable {


     private Long idpays;
     private String nom;
     private Set paysfilms = new HashSet(0);

    public Paysproduction() {
    }

	
    public Paysproduction(Long idpays, String nom) {
        this.idpays = idpays;
        this.nom = nom;
    }
    public Paysproduction(Long idpays, String nom, Set paysfilms) {
       this.idpays = idpays;
       this.nom = nom;
       this.paysfilms = paysfilms;
    }
   
    public Long getIdpays() {
        return this.idpays;
    }
    
    public void setIdpays(Long idpays) {
        this.idpays = idpays;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getPaysfilms() {
        return this.paysfilms;
    }
    
    public void setPaysfilms(Set paysfilms) {
        this.paysfilms = paysfilms;
    }




}


