package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * PaysfilmId generated by hbm2java
 */
public class PaysfilmId  implements java.io.Serializable {


     private String idpays;
     private String idfilm;

    public PaysfilmId() {
    }

    public PaysfilmId(String idpays, String idfilm) {
       this.idpays = idpays;
       this.idfilm = idfilm;
    }
   
    public String getIdpays() {
        return this.idpays;
    }
    
    public void setIdpays(String idpays) {
        this.idpays = idpays;
    }
    public String getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(String idfilm) {
        this.idfilm = idfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaysfilmId) ) return false;
		 PaysfilmId castOther = ( PaysfilmId ) other; 
         
		 return ( (this.getIdpays()==castOther.getIdpays()) || ( this.getIdpays()!=null && castOther.getIdpays()!=null && this.getIdpays().equals(castOther.getIdpays()) ) )
 && ( (this.getIdfilm()==castOther.getIdfilm()) || ( this.getIdfilm()!=null && castOther.getIdfilm()!=null && this.getIdfilm().equals(castOther.getIdfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpays() == null ? 0 : this.getIdpays().hashCode() );
         result = 37 * result + ( getIdfilm() == null ? 0 : this.getIdfilm().hashCode() );
         return result;
   }   


}


