package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * Paysfilm generated by hbm2java
 */
public class Paysfilm  implements java.io.Serializable {


     private PaysfilmId id;
     private Film film;
     private Paysproduction paysproduction;

    public Paysfilm() {
    }

    public Paysfilm(PaysfilmId id, Film film, Paysproduction paysproduction) {
       this.id = id;
       this.film = film;
       this.paysproduction = paysproduction;
    }
   
    public PaysfilmId getId() {
        return this.id;
    }
    
    public void setId(PaysfilmId id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Paysproduction getPaysproduction() {
        return this.paysproduction;
    }
    
    public void setPaysproduction(Paysproduction paysproduction) {
        this.paysproduction = paysproduction;
    }




}


