package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnefilm generated by hbm2java
 */
public class Personnefilm  implements java.io.Serializable {


     private Long idpersonne;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String lieunaissance;
     private Clob courtebiographie;
     private Set scenaristefilms = new HashSet(0);
     private Set acteurfilms = new HashSet(0);
     private Set films = new HashSet(0);

    public Personnefilm() {
    }

	
    public Personnefilm(Long idpersonne, String nom, String prenom, Date datenaissance, String lieunaissance, Clob courtebiographie) {
        this.idpersonne = idpersonne;
        this.nom = nom;
        this.prenom = prenom;
        this.datenaissance = datenaissance;
        this.lieunaissance = lieunaissance;
        this.courtebiographie = courtebiographie;
    }
    public Personnefilm(Long idpersonne, String nom, String prenom, Date datenaissance, String lieunaissance, Clob courtebiographie, Set scenaristefilms, Set acteurfilms, Set films) {
       this.idpersonne = idpersonne;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.lieunaissance = lieunaissance;
       this.courtebiographie = courtebiographie;
       this.scenaristefilms = scenaristefilms;
       this.acteurfilms = acteurfilms;
       this.films = films;
    }
   
    public Long getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(Long idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getLieunaissance() {
        return this.lieunaissance;
    }
    
    public void setLieunaissance(String lieunaissance) {
        this.lieunaissance = lieunaissance;
    }
    public Clob getCourtebiographie() {
        return this.courtebiographie;
    }
    
    public void setCourtebiographie(Clob courtebiographie) {
        this.courtebiographie = courtebiographie;
    }
    public Set getScenaristefilms() {
        return this.scenaristefilms;
    }
    
    public void setScenaristefilms(Set scenaristefilms) {
        this.scenaristefilms = scenaristefilms;
    }
    public Set getActeurfilms() {
        return this.acteurfilms;
    }
    
    public void setActeurfilms(Set acteurfilms) {
        this.acteurfilms = acteurfilms;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


