package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * ScenaristefilmId generated by hbm2java
 */
public class ScenaristefilmId  implements java.io.Serializable {


     private String idpersonne;
     private String idfilm;

    public ScenaristefilmId() {
    }

    public ScenaristefilmId(String idpersonne, String idfilm) {
       this.idpersonne = idpersonne;
       this.idfilm = idfilm;
    }
   
    public String getIdpersonne() {
        return this.idpersonne;
    }
    
    public void setIdpersonne(String idpersonne) {
        this.idpersonne = idpersonne;
    }
    public String getIdfilm() {
        return this.idfilm;
    }
    
    public void setIdfilm(String idfilm) {
        this.idfilm = idfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScenaristefilmId) ) return false;
		 ScenaristefilmId castOther = ( ScenaristefilmId ) other; 
         
		 return ( (this.getIdpersonne()==castOther.getIdpersonne()) || ( this.getIdpersonne()!=null && castOther.getIdpersonne()!=null && this.getIdpersonne().equals(castOther.getIdpersonne()) ) )
 && ( (this.getIdfilm()==castOther.getIdfilm()) || ( this.getIdfilm()!=null && castOther.getIdfilm()!=null && this.getIdfilm().equals(castOther.getIdfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpersonne() == null ? 0 : this.getIdpersonne().hashCode() );
         result = 37 * result + ( getIdfilm() == null ? 0 : this.getIdfilm().hashCode() );
         return result;
   }   


}


