package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1



/**
 * Scenaristefilm generated by hbm2java
 */
public class Scenaristefilm  implements java.io.Serializable {


     private ScenaristefilmId id;
     private Personnefilm personnefilm;
     private Film film;

    public Scenaristefilm() {
    }

    public Scenaristefilm(ScenaristefilmId id, Personnefilm personnefilm, Film film) {
       this.id = id;
       this.personnefilm = personnefilm;
       this.film = film;
    }
   
    public ScenaristefilmId getId() {
        return this.id;
    }
    
    public void setId(ScenaristefilmId id) {
        this.id = id;
    }
    public Personnefilm getPersonnefilm() {
        return this.personnefilm;
    }
    
    public void setPersonnefilm(Personnefilm personnefilm) {
        this.personnefilm = personnefilm;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }




}


