package clientfilm.entity;
// Generated Nov 13, 2021 7:14:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private Long idutilisateur;
     private Adresse adresse;
     private String nom;
     private String prenom;
     private String courriel;
     private String telephone;
     private Date datenaissance;
     private Date dateinscription;
     private String motdepasse;
     private String categorieutilisateur;
     private Set locationarchivees = new HashSet(0);
     private Set locationactives = new HashSet(0);

    public Utilisateur() {
    }

	
    public Utilisateur(Long idutilisateur, Adresse adresse, String nom, String prenom, String courriel, String telephone, Date datenaissance, String motdepasse, String categorieutilisateur) {
        this.idutilisateur = idutilisateur;
        this.adresse = adresse;
        this.nom = nom;
        this.prenom = prenom;
        this.courriel = courriel;
        this.telephone = telephone;
        this.datenaissance = datenaissance;
        this.motdepasse = motdepasse;
        this.categorieutilisateur = categorieutilisateur;
    }
    public Utilisateur(Long idutilisateur, Adresse adresse, String nom, String prenom, String courriel, String telephone, Date datenaissance, Date dateinscription, String motdepasse, String categorieutilisateur, Set locationarchivees, Set locationactives) {
       this.idutilisateur = idutilisateur;
       this.adresse = adresse;
       this.nom = nom;
       this.prenom = prenom;
       this.courriel = courriel;
       this.telephone = telephone;
       this.datenaissance = datenaissance;
       this.dateinscription = dateinscription;
       this.motdepasse = motdepasse;
       this.categorieutilisateur = categorieutilisateur;
       this.locationarchivees = locationarchivees;
       this.locationactives = locationactives;
    }
   
    public Long getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Long idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public Date getDateinscription() {
        return this.dateinscription;
    }
    
    public void setDateinscription(Date dateinscription) {
        this.dateinscription = dateinscription;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public String getCategorieutilisateur() {
        return this.categorieutilisateur;
    }
    
    public void setCategorieutilisateur(String categorieutilisateur) {
        this.categorieutilisateur = categorieutilisateur;
    }
    public Set getLocationarchivees() {
        return this.locationarchivees;
    }
    
    public void setLocationarchivees(Set locationarchivees) {
        this.locationarchivees = locationarchivees;
    }
    public Set getLocationactives() {
        return this.locationactives;
    }
    
    public void setLocationactives(Set locationactives) {
        this.locationactives = locationactives;
    }




}


